# Generated by Django 5.0.1 on 2024-02-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0004_remove_userfile_date_remove_userfile_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='profile_picture',
            field=models.FileField(default=None, null=True, upload_to='user/user_profile/'),
        ),
    ]
