# Generated by Django 5.0.1 on 2024-02-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0006_alter_userfile_pdf_file_alter_userfile_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='pdf_file',
            field=models.FileField(default=None, null=True, upload_to='user/pdf_files/'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='user_file',
            field=models.FileField(default=None, null=True, upload_to='user/user_files/'),
        ),
    ]
