# Generated by Django 5.0.1 on 2024-03-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userData', '0007_alter_userfile_pdf_file_alter_userfile_user_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='userName',
            new_name='username',
        ),
    ]
