# Generated by Django 5.0.1 on 2024-03-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(default='Defaultusername', max_length=121, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=290)),
                ('profile_picture', models.FileField(default=None, null=True, upload_to='user/user_profile/')),
            ],
        ),
        migrations.CreateModel(
            name='UserFileHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_file', models.FileField(default=None, null=True, upload_to='user/user_files/')),
                ('pdf_file', models.FileField(default=None, null=True, upload_to='user/pdf_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userinformation')),
            ],
        ),
    ]
