# Generated by Django 4.2.3 on 2023-11-04 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userlogin', '0002_userdata_name_userdata_profile_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='pdf_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=121)),
                ('file', models.FileField(default=None, null=True, upload_to='user_file/')),
                ('pdf_file', models.FileField(default=None, null=True, upload_to='pdf')),
                ('time', models.DateTimeField()),
                ('user_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userlogin.userdata')),
            ],
        ),
    ]
