# Generated by Django 4.2.3 on 2024-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_way', models.CharField(max_length=50)),
                ('contact_details', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Follow_Me',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
            ],
        ),
    ]
