# Generated by Django 4.2.3 on 2023-11-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_userdata_name_userdata_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='userName',
            field=models.CharField(default=None, max_length=121),
        ),
    ]
