# Generated by Django 4.2.3 on 2023-11-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0003_userdata_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='userName',
            field=models.CharField(default=None, max_length=121, null=True),
        ),
    ]
